services:
  # ============
  # Main Bot
  # ============
  zahra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zahra
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    volumes:
      - ./.logs:/app/.logs
      - ./.env:/app/.env:ro
      - ./.env.keys:/app/.env.keys:ro
    networks:
      - bot-network
    user: "1001:1001"

  postgres:
    image: postgres:16
    container_name: bot_postgres
    restart: always
    env_file:
      - .env_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network

  redis:
    image: redis:7
    container_name: bot_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env_db
    volumes:
      - redisdata:/data
    networks:
      - bot-network

volumes:
  pgdata:
  redisdata:

networks:
  bot-network:
    driver: bridge